# Splices the regenerated Core table (docs/core_table.tmp.md data rows) into
# docs/MAPPING.md between the BEGIN/END CORE TABLE markers. Reuses the existing
# CJK table-header line so no CJK is typed in this ASCII script. Writes UTF-8.

$ErrorActionPreference = 'Stop'
$mapFile = 'd:\Rust\cesium\cesium-rs\docs\MAPPING.md'
$tmpFile = 'd:\Rust\cesium\cesium-rs\docs\core_table.tmp.md'

$utf8 = New-Object System.Text.UTF8Encoding($false)
$lines = [System.IO.File]::ReadAllLines($mapFile, [System.Text.Encoding]::UTF8)
$tmp   = [System.IO.File]::ReadAllLines($tmpFile, [System.Text.Encoding]::UTF8)

# Data rows from temp file: skip the ASCII placeholder header (first 2 lines).
$dataRows = $tmp | Select-Object -Skip 2

# Reuse the existing CJK table header + separator lines from the current file.
$cjkHeader = $lines | Where-Object { $_ -match '^\| JS ' } | Select-Object -First 1
$separator = '| --- | --- | --- | --- |'

$beginIdx = -1; $endIdx = -1
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match 'BEGIN CORE TABLE') { $beginIdx = $i }
    if ($lines[$i] -match 'END CORE TABLE')   { $endIdx   = $i }
}
if ($beginIdx -lt 0 -or $endIdx -lt 0) { throw 'markers not found' }

# Also drop the old example-row mini table that sits above the BEGIN marker.
# It spans from the "<!-- 示例行 -->" comment line to the line before BEGIN.
$exIdx = -1
for ($i = 0; $i -lt $beginIdx; $i++) {
    if ($lines[$i] -match '\u793a\u4f8b\u884c') { $exIdx = $i }
}

$before = New-Object System.Collections.Generic.List[string]
$stopBefore = if ($exIdx -ge 0) { $exIdx } else { $beginIdx }
for ($i = 0; $i -lt $stopBefore; $i++) { $before.Add($lines[$i]) }

$block = New-Object System.Collections.Generic.List[string]
$block.Add('<!-- BEGIN CORE TABLE (auto-generated by gen_mapping_core.ps1) -->')
$block.Add($cjkHeader)
$block.Add($separator)
foreach ($r in $dataRows) { $block.Add($r) }
$block.Add('<!-- END CORE TABLE -->')

$after = New-Object System.Collections.Generic.List[string]
for ($i = $endIdx + 1; $i -lt $lines.Count; $i++) { $after.Add($lines[$i]) }

$result = New-Object System.Collections.Generic.List[string]
foreach ($l in $before) { $result.Add($l) }
# blank line separating heading text from the table block
$result.Add('')
foreach ($l in $block)  { $result.Add($l) }
foreach ($l in $after)  { $result.Add($l) }

[System.IO.File]::WriteAllLines($mapFile, $result, $utf8)
Write-Host ("Spliced {0} data rows. begin={1} end={2} example_removed={3}" -f $dataRows.Count, $beginIdx, $endIdx, ($exIdx -ge 0))
