[package]
name = "app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cesium-rust"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
workspace_crate.workspace = true
ui.workspace = true
actions_crate.workspace = true
theme.workspace = true
util.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
serde.workspace = true
serde_json.workspace = true
