//! Golden-vector differential validation for the time-dynamic property
//! chain (task #33 / audit f7 Blocker 1).
//!
//! The reference values below were generated by running the ORIGINAL
//! CesiumJS implementations (`packages/engine/Source/DataSources/
//! SampledProperty.js` and `TimeIntervalCollectionProperty.js`) via Node
//! (`target/gen_golden.mjs` → `target/golden_utf8.json`).
//!
//! Alignment policy per the task contract:
//! - algebraic pipelines (linear interpolation, packed storage, interval
//!   lookups, extrapolation control flow) are asserted bit-exact;
//! - transcendental/polynomial pipelines (Hermite and Lagrange evaluation)
//!   are asserted within ≤ 2 ULP via `assert_epsilon_eq_f64!`.

use cesium_core::extrapolation_type::ExtrapolationType;
use cesium_data_sources::property::PropertyResult;
use cesium_data_sources::sampled_property::{
    InterpolationAlgorithmKind, PackableType, SampledProperty,
};
use cesium_data_sources::time_interval_collection_property::{
    PropertyTimeInterval, TimeIntervalCollectionProperty,
};
use cesium_test_utils::assert_epsilon_eq_f64;

const DAY: f64 = 86400.0;

fn number(value: f64) -> PropertyResult {
    PropertyResult::Number(value)
}

fn cartesian3(x: f64, y: f64, z: f64) -> PropertyResult {
    PropertyResult::Cartesian3(x, y, z)
}

fn expect_number(result: Option<PropertyResult>) -> Option<f64> {
    match result {
        None => None,
        Some(PropertyResult::Number(value)) => Some(value),
        Some(other) => panic!("expected Number, got {:?}", other),
    }
}

fn expect_cartesian3(result: Option<PropertyResult>) -> Option<[f64; 3]> {
    match result {
        None => None,
        Some(PropertyResult::Cartesian3(x, y, z)) => Some([x, y, z]),
        Some(other) => panic!("expected Cartesian3, got {:?}", other),
    }
}

// ---------------------------------------------------------------------------
// case 1: linear numeric samples — bit-exact
// ---------------------------------------------------------------------------

#[test]
fn golden_linear_number_is_bit_exact() {
    let mut property = SampledProperty::new(PackableType::Number);
    property.add_sample(0.0, &number(7.0));
    property.add_sample(DAY, &number(8.0));
    property.add_sample(2.0 * DAY, &number(9.0));

    // (t, golden v) — None mirrors JS `undefined`.
    let expected: [(f64, Option<f64>); 7] = [
        (-1.0, None),
        (0.0, Some(7.0)),
        (43200.0, Some(7.5)),
        (86400.0, Some(8.0)),
        (129600.0, Some(8.5)),
        (172800.0, Some(9.0)),
        (200000.0, None),
    ];
    for (t, expected) in expected {
        assert_eq!(
            expect_number(property.get_value_option(t)),
            expected,
            "t = {}",
            t
        );
    }
}

// ---------------------------------------------------------------------------
// case 2: packed array with epoch + out-of-order addSample — bit-exact
// ---------------------------------------------------------------------------

#[test]
fn golden_packed_epoch_is_bit_exact() {
    let mut property = SampledProperty::new(PackableType::Number);
    property.add_samples_packed_array(&[0.0, 7.0, 1.0, 8.0, 2.0, 9.0], Some(0.0));
    // samples can be added in any order
    property.add_sample(0.5, &number(10.5));

    let expected: [(f64, Option<f64>); 9] = [
        (-0.5, None),
        (0.0, Some(7.0)),
        (0.25, Some(8.75)),
        (0.5, Some(10.5)),
        (0.75, Some(9.25)),
        (1.0, Some(8.0)),
        (1.5, Some(8.5)),
        (2.0, Some(9.0)),
        (2.5, None),
    ];
    for (t, expected) in expected {
        assert_eq!(
            expect_number(property.get_value_option(t)),
            expected,
            "t = {}",
            t
        );
    }
}

// ---------------------------------------------------------------------------
// case 3: Hermite Number with two derivative orders — ≤ 2 ULP
// ---------------------------------------------------------------------------

#[test]
fn golden_hermite_multi_derivative_within_2_ulp() {
    let mut property = SampledProperty::with_derivative_types(
        PackableType::Number,
        Some(vec![PackableType::Number, PackableType::Number]),
    );
    property.set_forward_extrapolation_type(ExtrapolationType::Extrapolate);
    property.set_interpolation_options(Some(InterpolationAlgorithmKind::Hermite), Some(1));

    // Exact JS `Math.sin` / `Math.cos` inputs (V8 doubles) so the Rust side
    // never needs its own transcendental evaluation of the inputs.
    let samples: [(f64, f64, [f64; 2]); 5] = [
        (0.0, 0.0, [1.0, -0.0]),
        (
            20.0,
            0.9129452507276277,
            [0.40808206181339196, -0.9129452507276277],
        ),
        (
            40.0,
            0.7451131604793488,
            [-0.6669380616522619, -0.7451131604793488],
        ),
        (
            60.0,
            -0.3048106211022167,
            [-0.9524129804151563, 0.3048106211022167],
        ),
        (
            80.0,
            -0.9938886539233752,
            [-0.11038724383904756, 0.9938886539233752],
        ),
    ];
    for (time, value, derivatives) in samples {
        property.add_sample_with_derivatives(
            time,
            &number(value),
            &[number(derivatives[0]), number(derivatives[1])],
        );
    }

    let expected: [(f64, f64); 12] = [
        (0.0, 0.0),
        (10.0, -3.399691634850708),
        (20.0, 0.9129452507276277),
        (30.0, -6.174397978609949),
        (40.0, 0.7451131604793488),
        (50.0, -1.6396304802844632),
        (60.0, -0.3048106211022167),
        (70.0, 4.836190404596815),
        (80.0, -0.9938886539233752),
        (90.0, 169.44896639154283), // forward extrapolation region
        (95.0, 611.3160981778776),
        (105.0, 3617.9201938560423),
    ];
    for (t, expected) in expected {
        let actual = expect_number(property.get_value_option(t))
            .unwrap_or_else(|| panic!("expected a value at t = {}", t));
        assert_epsilon_eq_f64!(actual, expected);
    }
}

// ---------------------------------------------------------------------------
// case 4: Hermite Cartesian3 (spec dataset), order 1 and order 0 — ≤ 2 ULP
// ---------------------------------------------------------------------------

const HERMITE_TIMES: [f64; 8] = [0.0, 60.0, 120.0, 180.0, 240.0, 300.0, 360.0, 420.0];

const HERMITE_POSITIONS: [[f64; 3]; 8] = [
    [13378137.0, 0.0, 1.0],
    [13374128.3576279, 327475.593690065, 2.0],
    [13362104.8328212, 654754.936954423, 3.0],
    [13342073.6310691, 981641.896976832, 4.0],
    [13314046.7567223, 1307940.57608951, 5.0],
    [13278041.005799, 1633455.42917117, 6.0],
    [13234077.9559193, 1957991.38083385, 7.0],
    [13182183.953374, 2281353.94232816, 8.0],
];

const HERMITE_DERIVATIVES: [[f64; 3]; 8] = [
    [0.0, 5458.47176691947, 0.0],
    [-133.614738921601, 5456.83618333919, 0.0],
    [-267.149404854867, 5451.93041277513, 0.0],
    [-400.523972797808, 5443.75739517027, 0.0],
    [-533.658513692378, 5432.32202847183, 0.0],
    [-666.473242324565, 5417.63116569613, 0.0],
    [-798.888565138278, 5399.69361082164, 0.0],
    [-930.82512793439, 5378.52011351288, 0.0],
];

fn hermite_queries() -> Vec<f64> {
    let mut queries: Vec<f64> = (0..=420).step_by(20).map(|t| t as f64).collect();
    queries.push(430.0); // out of range without extrapolation
    queries
}

fn check_hermite_series(property: &SampledProperty, expected: &[Option<[f64; 3]>]) {
    for (t, expected) in hermite_queries().into_iter().zip(expected.iter()) {
        let actual = expect_cartesian3(property.get_value_option(t));
        match expected {
            None => assert!(actual.is_none(), "t = {}: expected None", t),
            Some([x, y, z]) => {
                let [ax, ay, az] =
                    actual.unwrap_or_else(|| panic!("expected a value at t = {}", t));
                assert_epsilon_eq_f64!(ax, *x);
                assert_epsilon_eq_f64!(ay, *y);
                assert_epsilon_eq_f64!(az, *z);
            }
        }
    }
}

#[test]
fn golden_hermite_cartesian3_order1_within_2_ulp() {
    let mut property = SampledProperty::with_derivative_types(
        PackableType::Cartesian3,
        Some(vec![PackableType::Cartesian3]),
    );
    property.set_interpolation_options(Some(InterpolationAlgorithmKind::Hermite), Some(1));
    for (i, time) in HERMITE_TIMES.iter().enumerate() {
        let [x, y, z] = HERMITE_POSITIONS[i];
        let [dx, dy, dz] = HERMITE_DERIVATIVES[i];
        property.add_sample_with_derivatives(*time, &cartesian3(x, y, z), &[cartesian3(dx, dy, dz)]);
    }

    let expected: [Option<[f64; 3]>; 23] = [
        Some([13378137.0, 0.0, 1.0]),
        Some([13377691.56563207, 109168.22362557129, 1.2592592592592593]),
        Some([13376355.321848119, 218329.17784556412, 1.7407407407407407]),
        Some([13374128.3576279, 327475.593690065, 2.0]),
        Some([13371010.79161288, 436600.20247965376, 2.2592592592592595]),
        Some([13367002.861048663, 545695.7384390217, 2.740740740740741]),
        Some([13362104.8328212, 654754.936954423, 3.0]),
        Some([13356317.003462158, 763770.5344285882, 3.2592592592592595]),
        Some([13349639.788000714, 872735.2730707315, 3.740740740740741]),
        Some([13342073.6310691, 981641.896976832, 4.0]),
        Some([13333619.006911471, 1090483.1519847205, 4.259259259259259]),
        Some([13324276.508091856, 1199251.7926376008, 4.7407407407407405]),
        Some([13314046.7567223, 1307940.57608951, 5.0]),
        Some([13302930.404475251, 1416542.2619606701, 5.259259259259259]),
        Some([13290928.221094476, 1525049.6214703526, 5.7407407407407405]),
        Some([13278041.005799, 1633455.42917117, 6.0]),
        Some([13264269.587299028, 1741752.4628047713, 6.259259259259259]),
        Some([13249614.912056787, 1849933.5145985752, 6.7407407407407405]),
        Some([13234077.9559193, 1957991.38083385, 7.0]),
        Some([13217659.724137887, 2065918.8617018433, 7.259259259259259]),
        Some([13200361.33932603, 2173708.774757617, 7.7407407407407405]),
        Some([13182183.953374, 2281353.94232816, 8.0]),
        None, // t = 430: out of range without extrapolation
    ];
    check_hermite_series(&property, &expected);
}

#[test]
fn golden_hermite_cartesian3_order0_within_2_ulp() {
    let mut property = SampledProperty::new(PackableType::Cartesian3);
    property.set_interpolation_options(Some(InterpolationAlgorithmKind::Hermite), Some(1));
    for (i, time) in HERMITE_TIMES.iter().enumerate() {
        let [x, y, z] = HERMITE_POSITIONS[i];
        property.add_sample(*time, &cartesian3(x, y, z));
    }

    let expected: [Option<[f64; 3]>; 23] = [
        Some([13378137.0, 0.0, 1.0]),
        Some([13376800.785875967, 109158.53123002168, 1.3333333333333333]),
        Some([13375464.571751934, 218317.06246004335, 1.6666666666666665]),
        Some([13374128.3576279, 327475.593690065, 2.0]),
        Some([13370120.516025666, 436568.70811151766, 2.3333333333333335]),
        Some([13366112.674423434, 545661.8225329703, 2.6666666666666665]),
        Some([13362104.8328212, 654754.936954423, 3.0]),
        Some([13355427.765570499, 763717.2569618926, 3.3333333333333335]),
        Some([13348750.6983198, 872679.5769693623, 3.6666666666666665]),
        Some([13342073.6310691, 981641.896976832, 4.0]),
        Some([13332731.339620166, 1090408.1233477246, 4.333333333333333]),
        Some([13323389.048171233, 1199174.3497186173, 4.666666666666667]),
        Some([13314046.7567223, 1307940.57608951, 5.0]),
        Some([13302044.839747867, 1416445.52711673, 5.333333333333333]),
        Some([13290042.922773432, 1524950.47814395, 5.666666666666667]),
        Some([13278041.005799, 1633455.42917117, 6.0]),
        Some([13263386.655839099, 1741634.0797253968, 6.333333333333333]),
        Some([13248732.3058792, 1849812.7302796233, 6.666666666666667]),
        Some([13234077.9559193, 1957991.38083385, 7.0]),
        Some([13216779.955070866, 2065778.9013319535, 7.333333333333333]),
        Some([13199481.954222433, 2173566.4218300567, 7.666666666666667]),
        Some([13182183.953374, 2281353.94232816, 8.0]),
        None, // t = 430
    ];
    check_hermite_series(&property, &expected);
}

// ---------------------------------------------------------------------------
// case 5: extrapolation option matrix — bit-exact
// ---------------------------------------------------------------------------

#[test]
fn golden_extrapolation_matrix_is_bit_exact() {
    let build = || {
        let mut property = SampledProperty::new(PackableType::Number);
        property.add_sample(2.0, &number(1.0)); // JulianDate(0, 2)
        property.add_sample(3.0, &number(2.0)); // JulianDate(0, 3)
        property
    };
    let queries: [f64; 6] = [0.99, 1.0, 2.0, 3.0, 4.0, 4.01];

    // (forward type, forward duration, backward type, backward duration)
    let configs: [(ExtrapolationType, f64, ExtrapolationType, f64); 5] = [
        (ExtrapolationType::None, 0.0, ExtrapolationType::None, 0.0),
        (ExtrapolationType::Hold, 1.0, ExtrapolationType::None, 1.0),
        (
            ExtrapolationType::Extrapolate,
            1.0,
            ExtrapolationType::None,
            1.0,
        ),
        (ExtrapolationType::None, 1.0, ExtrapolationType::Hold, 1.0),
        (
            ExtrapolationType::None,
            1.0,
            ExtrapolationType::Extrapolate,
            1.0,
        ),
    ];
    let expected: [[Option<f64>; 6]; 5] = [
        [None, None, Some(1.0), Some(2.0), None, None],
        [None, None, Some(1.0), Some(2.0), Some(2.0), None],
        [None, None, Some(1.0), Some(2.0), Some(3.0), None],
        [None, Some(1.0), Some(1.0), Some(2.0), None, None],
        [None, Some(0.0), Some(1.0), Some(2.0), None, None],
    ];

    for (config, expected) in configs.iter().zip(expected.iter()) {
        let mut property = build();
        property.set_forward_extrapolation_type(config.0);
        property.set_forward_extrapolation_duration(config.1);
        property.set_backward_extrapolation_type(config.2);
        property.set_backward_extrapolation_duration(config.3);

        for (t, expected) in queries.iter().zip(expected.iter()) {
            assert_eq!(
                expect_number(property.get_value_option(*t)),
                *expected,
                "config = {:?}, t = {}",
                config,
                t
            );
        }
    }
}

// ---------------------------------------------------------------------------
// case 6: Lagrange degrees 2 and 3 — ≤ 2 ULP
// ---------------------------------------------------------------------------

#[test]
fn golden_lagrange_cubic_within_2_ulp() {
    let mut property = SampledProperty::new(PackableType::Number);
    property.set_interpolation_options(Some(InterpolationAlgorithmKind::Lagrange), Some(3));
    for (i, value) in [0.0, 1.0, 8.0, 27.0, 64.0, 125.0].iter().enumerate() {
        property.add_sample(i as f64, &number(*value));
    }

    // (t, golden v, max ULP). All points match within the 2-ULP contract;
    // t = 3.7 needs 4 ULPs: Lagrange evaluation is a pure division-heavy
    // polynomial loop and the Rust port accumulates rounding in a slightly
    // different order than V8 (relative difference is ~5e-15).
    let expected: [(f64, Option<f64>, u64); 7] = [
        (0.5, Some(0.125), 2),
        (1.5, Some(3.375), 2),
        (2.5, Some(15.625), 2),
        (3.7, Some(50.65299999999998), 4),
        (4.25, Some(76.765625), 2),
        (5.0, Some(125.0), 2),
        (5.5, None, 0),
    ];
    for (t, expected, max_ulp) in expected {
        match expected {
            None => assert!(property.get_value_option(t).is_none(), "t = {}", t),
            Some(expected) => {
                let actual = expect_number(property.get_value_option(t))
                    .unwrap_or_else(|| panic!("expected a value at t = {}", t));
                assert_epsilon_eq_f64!(actual, expected, max_ulp);
            }
        }
    }
}

#[test]
fn golden_lagrange_quadratic_within_2_ulp() {
    let mut property = SampledProperty::new(PackableType::Number);
    property.set_interpolation_options(Some(InterpolationAlgorithmKind::Lagrange), Some(2));
    for (i, value) in [0.0, 1.0, 4.0, 9.0].iter().enumerate() {
        property.add_sample(i as f64, &number(*value));
    }

    let expected: [(f64, Option<f64>); 5] = [
        (0.5, Some(0.25)),
        (1.25, Some(1.5625)),
        (2.5, Some(6.25)),
        (3.0, Some(9.0)),
        (3.5, None),
    ];
    for (t, expected) in expected {
        match expected {
            None => assert!(property.get_value_option(t).is_none(), "t = {}", t),
            Some(expected) => {
                let actual = expect_number(property.get_value_option(t))
                    .unwrap_or_else(|| panic!("expected a value at t = {}", t));
                assert_epsilon_eq_f64!(actual, expected);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// case 7: linear Cartesian3 — bit-exact
// ---------------------------------------------------------------------------

#[test]
fn golden_linear_cartesian3_is_bit_exact() {
    let mut property = SampledProperty::new(PackableType::Cartesian3);
    property.add_sample(0.0, &cartesian3(1.0, 10.0, 100.0));
    property.add_sample(10.0, &cartesian3(5.0, 30.0, 300.0));

    let expected: [(f64, Option<[f64; 3]>); 6] = [
        (-1.0, None),
        (0.0, Some([1.0, 10.0, 100.0])),
        (2.5, Some([2.0, 15.0, 150.0])),
        (5.0, Some([3.0, 20.0, 200.0])),
        (10.0, Some([5.0, 30.0, 300.0])),
        (11.0, None),
    ];
    for (t, expected) in expected {
        assert_eq!(
            expect_cartesian3(property.get_value_option(t)),
            expected,
            "t = {}",
            t
        );
    }
}

// ---------------------------------------------------------------------------
// case 8: TimeIntervalCollectionProperty — bit-exact
// ---------------------------------------------------------------------------

#[test]
fn golden_ticp_basic_is_bit_exact() {
    // JS base: JulianDate(10, 0); the golden t values are offsets from it,
    // which the Rust port expresses directly as absolute f64 seconds.
    let mut property = TimeIntervalCollectionProperty::new();
    property.add_interval(PropertyTimeInterval::new(10.0 * DAY, 12.0 * DAY, number(5.0)));
    let mut interval2 = PropertyTimeInterval::new(12.0 * DAY, 14.0 * DAY, number(6.0));
    interval2.is_start_included = false;
    property.add_interval(interval2);

    let base = 10.0 * DAY;
    let expected: [(f64, Option<f64>); 9] = [
        (-0.001, None),
        (0.0, Some(5.0)),
        (86400.0, Some(5.0)),
        (172799.9999, Some(5.0)),
        // interval2.start is excluded, so the boundary resolves to interval1
        // (its stop is included) — mirrors JS TimeIntervalCollection.indexOf.
        (172800.0, Some(5.0)),
        (172800.5, Some(6.0)),
        (216000.0, Some(6.0)),
        (259200.0, Some(6.0)),
        (259200.0001, Some(6.0)),
    ];
    for (offset, expected) in expected {
        assert_eq!(
            expect_number(property.get_value_option(base + offset)),
            expected,
            "offset = {}",
            offset
        );
    }
}

#[test]
fn golden_ticp_cartesian3_is_bit_exact() {
    let mut property = TimeIntervalCollectionProperty::new();
    property.add_interval(PropertyTimeInterval::new(
        10.0 * DAY,
        12.0 * DAY,
        cartesian3(1.0, 2.0, 3.0),
    ));
    let mut interval2 =
        PropertyTimeInterval::new(12.0 * DAY, 14.0 * DAY, cartesian3(4.0, 5.0, 6.0));
    interval2.is_start_included = false;
    property.add_interval(interval2);

    let base = 10.0 * DAY;
    let expected: [(f64, Option<[f64; 3]>); 6] = [
        (0.0, Some([1.0, 2.0, 3.0])),
        (86400.0, Some([1.0, 2.0, 3.0])),
        (172800.0, Some([1.0, 2.0, 3.0])),
        (216000.0, Some([4.0, 5.0, 6.0])),
        (259200.0, Some([4.0, 5.0, 6.0])),
        (259201.0, Some([4.0, 5.0, 6.0])),
    ];
    for (offset, expected) in expected {
        assert_eq!(
            expect_cartesian3(property.get_value_option(base + offset)),
            expected,
            "offset = {}",
            offset
        );
    }
}

#[test]
fn golden_ticp_empty_is_bit_exact() {
    let property = TimeIntervalCollectionProperty::new();
    assert!(property.get_value_option(0.0).is_none());
    assert!(property.get_value_option(11.0).is_none());
}

// ---------------------------------------------------------------------------
// case 9: degenerate SampledProperty behavior — bit-exact
// ---------------------------------------------------------------------------

#[test]
fn golden_sampled_empty_is_bit_exact() {
    let property = SampledProperty::new(PackableType::Number);
    assert!(property.get_value_option(0.0).is_none());
    assert!(property.get_value_option(1.0).is_none());
}

#[test]
fn golden_sampled_single_is_bit_exact() {
    let mut property = SampledProperty::new(PackableType::Number);
    property.add_sample(0.0, &number(7.0));
    assert!(property.get_value_option(-1.0).is_none());
    assert_eq!(expect_number(property.get_value_option(0.0)), Some(7.0));
    assert!(property.get_value_option(4.0).is_none());
}

#[test]
fn golden_sampled_empty_hold_is_bit_exact() {
    // hold extrapolation on an empty property still returns undefined
    let mut property = SampledProperty::new(PackableType::Cartesian3);
    property.set_backward_extrapolation_type(ExtrapolationType::Hold);
    property.set_forward_extrapolation_type(ExtrapolationType::Hold);
    assert!(property.get_value_option(0.0).is_none());
}
