//! Mirror of `packages/engine/Specs/Core/CorridorOutlineGeometrySpec.js`.
//!
//! Ports the `createGeometry`-returns-undefined, positions, and
//! extruded positions tests.
//!
//! DEVIATION: JS uses an options object; the Rust port uses
//! `CorridorOutlineGeometry::new` with positional parameters.

use cesium_core::cartesian3::Cartesian3;
use cesium_core::corner_type::CornerType;
use cesium_core::corridor_outline_geometry::{create_geometry, CorridorOutlineGeometry};
use cesium_core::index_datatype::IndexStorage;

#[test]
fn create_geometry_returns_undefined_without_2_unique_positions() {
    let positions =
        Cartesian3::from_degrees_array(&[90.0, -30.0, 90.0, -30.0], None, None);
    let geometry = create_geometry(&CorridorOutlineGeometry::new(
        positions,
        10000.0,
        None,
        None,
        None,
        None,
        None,
        None,
    ));
    assert!(geometry.is_none());
}

#[test]
fn computes_positions() {
    let positions =
        Cartesian3::from_degrees_array(&[90.0, -30.0, 90.0, -35.0], None, None);
    let m = create_geometry(&CorridorOutlineGeometry::new(
        positions,
        30000.0,
        None,
        None,
        None,
        Some(CornerType::Mitered),
        None,
        None,
    ));
    let m = m.expect("geometry should not be None");

    // 6 left + 6 right
    assert_eq!(m.attributes.get("position").unwrap().values.len(), 12 * 3);
    assert_eq!(m.indices.as_ref().unwrap().len(), 12 * 2);
}

#[test]
fn computes_positions_extruded() {
    let positions =
        Cartesian3::from_degrees_array(&[90.0, -30.0, 90.0, -35.0], None, None);
    let m = create_geometry(&CorridorOutlineGeometry::new(
        positions,
        30000.0,
        None,
        None,
        Some(30000.0), // extrudedHeight
        Some(CornerType::Mitered),
        None,
        None,
    ));
    let m = m.expect("geometry should not be None");

    // 6 positions * 4 for a box at each position
    assert_eq!(m.attributes.get("position").unwrap().values.len(), 24 * 3);
    // 5 segments * 4 lines per segment + 4 lines * 2 ends
    assert_eq!(m.indices.as_ref().unwrap().len(), 28 * 2);
}

/// CZ-01 residual differential closure: `combine` wallIndices first-corner
/// index. Goldens generated by `golden_corridor_outline.mjs` (CesiumJS
/// `packages/engine` source, Node).
mod corridor_outline_golden_diff {
    use super::*;

    const GOLDEN: &str = include_str!("golden_corridor_outline.json");

    fn read_indices(storage: &IndexStorage) -> Vec<u32> {
        match storage {
            IndexStorage::U16(v) => v.iter().map(|&x| x as u32).collect(),
            IndexStorage::U32(v) => v.to_vec(),
        }
    }

    fn run_case(
        name: &str,
        positions: Vec<Cartesian3>,
        height: Option<f64>,
        extruded_height: Option<f64>,
        corner_type: CornerType,
    ) {
        let golden: serde_json::Value = serde_json::from_str(GOLDEN).unwrap();
        let case = &golden[name];

        let geometry = create_geometry(&CorridorOutlineGeometry::new(
            positions,
            100000.0,
            None,
            height,
            extruded_height,
            Some(corner_type),
            None,
            None,
        ))
        .expect("geometry should not be None");

        // Position count (22/36/2*... golden positionCount is per-vertex).
        let pos_count = case["positionCount"].as_u64().unwrap() as usize;
        assert_eq!(
            geometry.attributes.get("position").unwrap().values.len() / 3,
            pos_count,
            "{name}: position count mismatch"
        );

        // First 12 position values (covers top + first extruded duplicate).
        let head = case["positionsHead"].as_array().unwrap();
        let values = &geometry.attributes.get("position").unwrap().values;
        for (i, g) in head.iter().enumerate() {
            let expected = g.as_f64().unwrap();
            assert!(
                (values[i] - expected).abs() <= 1e-8 * expected.abs().max(1.0),
                "{name}: position[{i}] {} != {expected}",
                values[i]
            );
        }

        // Full index buffer — this is where the combine wallIndices
        // first-corner ±1 defect surfaces.
        let expected_indices: Vec<u32> = case["indices"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        let actual_indices = read_indices(geometry.indices.as_ref().unwrap());
        assert_eq!(
            actual_indices, expected_indices,
            "{name}: index buffer mismatch"
        );

        // Bounding sphere.
        let bs = case["boundingSphere"].as_array().unwrap();
        let sphere = geometry
            .bounding_sphere
            .as_ref()
            .expect("bounding sphere should be present");
        let actual = [
            sphere.center.x,
            sphere.center.y,
            sphere.center.z,
            sphere.radius,
        ];
        for (i, g) in bs.iter().enumerate() {
            let expected = g.as_f64().unwrap();
            assert!(
                (actual[i] - expected).abs() <= 1e-8 * expected.abs().max(1.0),
                "{name}: boundingSphere[{i}] {} != {expected}",
                actual[i]
            );
        }
    }

    #[test]
    fn beveled_extruded_one_corner_matches_cesiumjs_golden() {
        run_case(
            "beveled_extruded_one_corner",
            Cartesian3::from_degrees_array(&[0.0, 0.0, 2.0, 0.0, 2.0, 2.0], None, None),
            Some(100.0),
            Some(0.0),
            CornerType::Beveled,
        );
    }

    #[test]
    fn mitered_extruded_two_corners_matches_cesiumjs_golden() {
        run_case(
            "mitered_extruded_two_corners",
            Cartesian3::from_degrees_array(
                &[0.0, 0.0, 2.0, 0.0, 2.0, 2.0, 4.0, 2.0],
                None,
                None,
            ),
            Some(200.0),
            Some(0.0),
            CornerType::Mitered,
        );
    }

    #[test]
    fn rounded_flat_one_corner_matches_cesiumjs_golden() {
        run_case(
            "rounded_flat_one_corner",
            Cartesian3::from_degrees_array(&[0.0, 0.0, 2.0, 0.0, 2.0, 2.0], None, None),
            Some(0.0),
            None,
            CornerType::Rounded,
        );
    }
}
