[package]
name = "cesium-bevy-render"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
glam.workspace = true
cesium-geospatial.workspace = true
cesium-imagery.workspace = true
cesium-terrain.workspace = true
cesium-tileset.workspace = true
cesium-scene.workspace = true
cesium-datasource.workspace = true
cesium-material.workspace = true
cesium-ports-driven.workspace = true
