[package]
name = "cesium-decoders"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
draco = []

[dependencies]
cesium-geospatial.workspace = true
cesium-terrain.workspace = true
cesium-tileset.workspace = true
cesium-ports-driven.workspace = true
glam.workspace = true
image = { workspace = true, features = ["png", "jpeg", "webp"] }
thiserror.workspace = true
flate2 = "1"

